name: GitHub Actions Hello World

# 1. Define the trigger event
on:
  push:
    branches: [ "main" ]

# 2. Group the tasks together
jobs:
  test:
    # Specify the operating system server environment
    runs-on: ubuntu-latest

    # 3. List individual tasks sequentially
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm test


  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Do vercel pull
        run: vercel pull --environment=production --yes --token=$VERCEL_TOKEN

      - name: Debug step
        run: ls -la .vercel

      - name: Build
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Vercel deploy
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
